channels:
  - defaults
  - conda-forge
  - ranaroussi
  - anaconda
  - quantopian
dependencies:
  - pip
  - xarray
  - xlrd
  - xlsxwriter
  - ipywidgets
  - openpyxl
  - numpy
  - pandas
  - scipy
  - matplotlib
  - dask
  - plotly
  - gunicorn
  - dash-core-components
  - dash-html-components
  - dash
  - beautifulsoup4
  - statsmodels
  - quandl
  - pystore
  - yfinance
  - quantstats
  - scikit-learn
  - xgboost
  - pip:
    - chart_studio
    - monthdelta
    - PyWavelets
    - requests-html
    - python-dotenv
    - yahoo_fin
    - QuantLib
    - iexfinance
    - ezibpy
    - stocker
    - bert-tensorflow
    - git+https://github.com/yhilpisch/dx#egg=dx
    - "mxnet>=1.6"
    - tensorflow
    - ta